name: AWS EC2 Deploy

on:
  workflow_run:
    workflows:
      - Dockerhub Image Build and Push
    types:
      - completed

  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.CLAVE_EC2 }}
          HOSTNAME: ${{ secrets.IP_EC2 }}
          USER_NAME: ${{ secrets.USER_EC2 }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            echo "Connected to EC2"

            # Detener y eliminar contenedor anterior, si existe
            docker stop api-rios || true
            docker rm api-rios || true
            docker rmi pikatostes/api-rios || true

            # Ejecutar nuevo contenedor
            docker run -d -p 80:80 --name api-rios pikatostes/api-rios
          EOF
