name: AWS EC2 Deploy
on:
  workflow_run:
    workflows: 
    - Dockerhub Image Build and Push
    types:
    - completed

  push:
    branches: [ main ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.CLAVE_EC2 }}
          HOSTNAME : ${{ secrets.IP_EC2 }}
          USER_NAME : ${{ secrets.USER_EC2 }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key
          ${USER_NAME}@${HOSTNAME} '

          # Now we have got the access of EC2 and we will start the deploy
          .
          docker stop web1 && docker rm web1 && docker rmi
          dockeruser/galeria
          docker run -d -p 80:80 --name web1 dockeruser/galeria
          '